spring:
  application:
    name: bright-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/bright_tracker
    username: bright_tracker
    password: bright_tracker

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/bright-tracker