spring:
  application:
    name: bright-tracker

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bright_tracker}
    username: ${DB_USERNAME:bright_tracker}
    password: ${DB_PASSWORD:bright_tracker}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/bright-tracker